window.JOB_SESSIONS = [
  {
    "id": "2026-06-04_12d",
    "date": "2026-06-04",
    "window": "12d",
    "crawled": 100,
    "survived": 1,
    "drop_log": {
      "already-shown-prior-run": 63,
      "no-sponsorship": 6,
      "no-sponsorship-ai+text": 2,
      "defense-employer": 4,
      "yoe>=4-required": 9,
      "citizenship/clearance": 7,
      "non-US": 4,
      "duplicate-in-run": 4
    },
    "source": "apify:fantastic-jobs/career-site-job-listing-api",
    "jobs": [
      {
        "rank": 1,
        "score": 57,
        "title": "Investment Team Forward Deployed Engineer, BCTO",
        "company": "Bain Capital",
        "url": "https://baincapital.wd1.myworkdayjobs.com/External_Private/job/Boston/Embedded-AI-Strategist--Tech-Opportunities_REQ_108087",
        "location": "Boston, MA",
        "arrangement": "On-site",
        "salary": "$95–$110k",
        "posted": "1 day ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Collaborate with investment professionals to identify and implement AI tools that enhance the investment process. Prototype and evaluate AI solutions to improve decision-making and team efficiency."
      }
    ]
  },
  {
    "id": "2026-06-04_1d",
    "date": "2026-06-04",
    "window": "1d",
    "crawled": 34,
    "survived": 1,
    "drop_log": {
      "already-shown-prior-run": 20,
      "no-sponsorship": 3,
      "no-sponsorship-ai+text": 3,
      "defense-employer": 4,
      "yoe>=4-required": 2,
      "citizenship/clearance": 1
    },
    "source": "apify:fantastic-jobs/career-site-job-listing-api",
    "jobs": [
      {
        "rank": 1,
        "score": 56,
        "title": "Machine Learning Engineer II",
        "company": "Capital Group",
        "url": "https://capgroup.wd1.myworkdayjobs.com/capitalgroupcareers/job/Seattle/Machine-Learning-Engineer-II_JR6608",
        "location": "Irvine, CA / Los Angeles, CA / +1",
        "arrangement": "Hybrid",
        "salary": "$159–$255k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, implement, and maintain state-of-the-art machine learning models and data pipelines to enhance investment processes. Collaborate with senior investment professionals to conduct applied research and deploy financial models into production."
      }
    ]
  },
  {
    "id": "2026-06-02_6d",
    "date": "2026-06-02",
    "window": "6d",
    "crawled": 100,
    "survived": 63,
    "drop_log": {
      "no-sponsorship": 7,
      "no-sponsorship-ai+text": 2,
      "defense-employer": 4,
      "yoe>=4-required": 9,
      "citizenship/clearance": 7,
      "non-US": 4,
      "duplicate-in-run": 4
    },
    "source": "apify:fantastic-jobs/career-site-job-listing-api",
    "jobs": [
      {
        "rank": 1,
        "score": 93,
        "title": "Machine Learning Engineer",
        "company": "10a Labs",
        "url": "https://job-boards.greenhouse.io/10alabs/jobs/4273194009",
        "location": "Washington, DC",
        "arrangement": "Remote",
        "salary": "$130–$200k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, train, and deploy machine learning models across multimodal domains for safety, security, and intelligence applications. Build agentic systems and evaluation pipelines to measure model reliability and safety in production environments."
      },
      {
        "rank": 2,
        "score": 86,
        "title": "Generative AI Engineer",
        "company": "Artisan Management LLC",
        "url": "https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=2e854aaa-dd21-4f05-9004-21b747cee489&jobId=567699",
        "location": "Asheville, NC",
        "arrangement": "Remote",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, build, and deploy production-grade Generative AI systems and agentic architectures using AWS. Collaborate with clients to translate ambiguous requirements into secure, measurable, and scalable AI solutions."
      },
      {
        "rank": 3,
        "score": 85,
        "title": "Agentic AI Engineer",
        "company": "Fervo Energy",
        "url": "https://recruiting.paylocity.com/Recruiting/Jobs/Details/4199292",
        "location": "Houston, TX",
        "arrangement": "Hybrid",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy end-to-end agentic AI workflows and RAG-based architectures to automate operational capabilities for geothermal energy production. Establish reusable patterns for retrieval, semantic grounding, and agent orchestration using Azure, Databricks, and Snowflake."
      },
      {
        "rank": 4,
        "score": 84,
        "title": "Machine Learning Engineer III, Core Agents",
        "company": "Box",
        "url": "https://job-boards.greenhouse.io/boxinc/jobs/7962270",
        "location": "Redwood City, CA",
        "arrangement": "Hybrid",
        "salary": "$176–$220k",
        "posted": "-2 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and evaluate foundational AI agents for the Box ecosystem, focusing on intent detection, RAG, and multi-agent orchestration. Collaborate with platform engineers to ensure secure, scalable deployment and translate enterprise use cases into agentic solutions."
      },
      {
        "rank": 5,
        "score": 84,
        "title": "Software Engineer — AI Operations & Platform Development",
        "company": "SilverStay",
        "url": "https://silverstay.applytojob.com/apply/aWvdMHlWH9/Software-Engineer-AI-Operations-Platform-Development",
        "location": "Baltimore, MD",
        "arrangement": "Remote",
        "salary": "$80–$95k",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The role is split between maintaining and extending the SilverStay platform codebase and developing AI-powered internal automation workflows. Responsibilities include managing AWS serverless infrastructure and optimizing AI tools to reduce repetitive manual tasks for the internal"
      },
      {
        "rank": 6,
        "score": 84,
        "title": "Forward-Deployed AI Engineer",
        "company": "H.I.G. Capital",
        "url": "https://higcapital.wd5.myworkdayjobs.com/LinkedIn/job/Miami---Remote/Forward-Deployed-AI-Specialist_JOBREQ-279-2",
        "location": "San Francisco, CA / New York, NY",
        "arrangement": "Remote",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The Forward-Deployed AI Specialist will design, build, and deploy AI-powered automation solutions to drive measurable business impact across portfolio companies. This role involves managing vendor relationships, training end users, and delivering ROI-focused projects within compr"
      },
      {
        "rank": 7,
        "score": 83,
        "title": "Agentic AI Engineer for Aerospace (Entry Level)",
        "company": "Capgemini",
        "url": "https://careers.capgemini.com/job/Bellevue%2C-WA-Agentic-AI-Engineer-for-Aerospace-%28Entry-Level%29-WA-98004/1390570533/",
        "location": "Bellevue, WA",
        "arrangement": "Hybrid",
        "salary": "$44–$106k",
        "posted": "-1 days ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Design and develop LLM-based intelligent agents and RAG pipelines to automate engineering workflows for aerospace and automotive customers. Integrate MBSE, CAD, and PLM systems to enable digital thread capabilities and decision support."
      },
      {
        "rank": 8,
        "score": 80,
        "title": "Agentic AI Engineer",
        "company": "Cadence Design Systems",
        "url": "https://cadence.wd1.myworkdayjobs.com/External_Careers/job/CARY/Agentic-AI-Engineer_R55029",
        "location": "Cary, NC",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Develop and optimize agentic AI systems for silicon design, focusing on model training, retrieval pipelines, and knowledge graph tuning. Implement production-ready agent tools and data pipelines to accelerate chip design processes."
      },
      {
        "rank": 9,
        "score": 78,
        "title": "Forward Deployed Engineer",
        "company": "Stack Overflow",
        "url": "http://stackoverflow.co/company/work-here/7772964?gh_jid=7772964",
        "location": "United States",
        "arrangement": "Remote",
        "salary": "$180–$190k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Lead the technical delivery and optimization of Stack Internal deployments for enterprise customers. Develop delivery playbooks, build AI-powered integrations, and mentor future engineers to scale professional services."
      },
      {
        "rank": 10,
        "score": 78,
        "title": "Machine Learning Engineer",
        "company": "SAP",
        "url": "https://jobs.sap.com/job/Palo-Alto-Machine-Learning-Engineer-CA-94304/1400586833/",
        "location": "Stanford, CA",
        "arrangement": "Hybrid",
        "salary": "$107–$229k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and implement GenAI projects by combining Large Language Models with Knowledge Graphs to enhance SAP applications. Collaborate with data scientists to build cutting-edge tools and provide technical feasibility analysis for innovative AI features."
      },
      {
        "rank": 11,
        "score": 78,
        "title": "Internship - Research Engineer",
        "company": "Smule",
        "url": "https://smule.bamboohr.com/careers/30",
        "location": "Salt Lake City, UT",
        "arrangement": "Remote",
        "salary": "",
        "posted": "today",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Design and maintain research infrastructure, including distributed training pipelines and evaluation frameworks. Collaborate with scientists to optimize model architectures and ensure the reproducibility of research results."
      },
      {
        "rank": 12,
        "score": 77,
        "title": "AI Engineer",
        "company": "burfordcap",
        "url": "https://careers.burfordcapital.com/job/New-York-AI-Engineer-NY-10017/1362639400/",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "$130–$150k",
        "posted": "today",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "The AI Engineer will build and enhance AI-driven systems for processing real-time legal documents, ensuring system reliability and scalability across complex data pipelines. They will also collaborate with underwriting and business development teams to translate needs into effect"
      },
      {
        "rank": 13,
        "score": 77,
        "title": "AI Engineer - Forward Deployed",
        "company": "Edison Scientific",
        "url": "https://jobs.ashbyhq.com/Edison%20Scientific/3edadf80-f296-472c-8f42-012d20ef50c6",
        "location": "San Francisco, CA / Boston, MA / +1",
        "arrangement": "Remote",
        "salary": "$200–$350k",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The role involves being embedded at client sites to map scientific workflows and implement production-ready AI agent integrations. You will act as the technical bridge between customers and internal engineering teams to shape the product roadmap."
      },
      {
        "rank": 14,
        "score": 77,
        "title": "AI Engineer - Data Intelligence",
        "company": "Clarium",
        "url": "https://jobs.ashbyhq.com/clarium/83332693-7e11-41db-8b62-8225cb818abf",
        "location": "United States",
        "arrangement": "Remote",
        "salary": "$150–$180k",
        "posted": "today",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Build and maintain the master data enrichment pipeline, focusing on classification and entity resolution workflows using deterministic logic and LLMs. Develop evaluation harnesses and regression suites to ensure high data quality and pipeline reliability."
      },
      {
        "rank": 15,
        "score": 76,
        "title": "Applied AI Engineer",
        "company": "Becoming",
        "url": "https://jobs.workable.com/view/552gk9ZtEAqSNJVzUKiPM4/applied-ai-engineer-in-san-francisco-at-becoming",
        "location": "San Francisco, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and develop production-grade software, data pipelines, and cloud infrastructure to power a biological intelligence platform. Collaborate with scientists and researchers to transform experimental data into predictive models of living systems."
      },
      {
        "rank": 16,
        "score": 74,
        "title": "AI Engineer in ML Data",
        "company": "Logical Intelligence",
        "url": "https://job-boards.greenhouse.io/logicalintelligence/jobs/4117916009",
        "location": "San Francisco, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The role involves designing and refining data and ML pipelines necessary for the scaled distributed training and validation of machine learning models. Responsibilities include researching new reasoning algorithms, developing benchmarking tools, and building infrastructure for da"
      },
      {
        "rank": 17,
        "score": 74,
        "title": "Professional, Software Engineer - AI",
        "company": "MVP Health Care",
        "url": "https://mvphealthcare.wd5.myworkdayjobs.com/mvphealthcare/job/Schenectady-NY/Professional--Software-Engineer---AI_JR100212",
        "location": "Schenectady, NY",
        "arrangement": "Hybrid",
        "salary": "$69–$92k",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, develop, and maintain scalable AI-focused software solutions and machine learning models for production environments. Implement MLOps practices, data pipelines, and integrate AI models into applications via APIs and microservices."
      },
      {
        "rank": 18,
        "score": 73,
        "title": "Forward Deployed Engineer, AI Enablement (UR & MiR, North Reading, MA)",
        "company": "Teradyne",
        "url": "https://jobs.teradyne.com/Teradyne/job/North-Reading-Forward-Deployed-Engineer%2C-AI-Enablement-%28UR-&-MiR%2C-North-Reading%2C-MA%29-MA/1396537200/",
        "location": "North Reading, MA",
        "arrangement": "On-site",
        "salary": "$170–$272k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy AI-augmented workflows and conversational AI systems to improve business metrics across various departments. Collaborate with stakeholders to translate AI capabilities into measurable business value and lead solutions from concept to production."
      },
      {
        "rank": 19,
        "score": 73,
        "title": "Associate AI Engineer (6-month contract)",
        "company": "Board International",
        "url": "https://boardinternationalsa.applytojob.com/apply/LeNTy0zfun/Associate-AI-Engineer-6month-Contract",
        "location": "Boston, MA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, build, and deploy AI-powered solutions and prototypes to improve business processes and operational efficiency. Partner with various business functions to implement AI-enabled workflows and integrate them with enterprise platforms."
      },
      {
        "rank": 20,
        "score": 73,
        "title": "Machine Learning Engineer",
        "company": "Multi Media LLC",
        "url": "https://jobs.workable.com/view/bqkqSAJN2W35yHL1WmQ5C9/remote-machine-learning-engineer-in-united-states-at-multi-media-llc",
        "location": "United States",
        "arrangement": "Remote",
        "salary": "$180–$200k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and maintain production-grade machine learning systems for search, recommendations, and personalization on a global-scale platform. Collaborate with cross-functional teams to translate business needs into scalable ML solutions that improve user engagement and discovery."
      },
      {
        "rank": 21,
        "score": 72,
        "title": "BestX AI Engineer, Full-time Internship (July - Dec 2026)",
        "company": "State Street",
        "url": "https://statestreet.wd1.myworkdayjobs.com/Global/job/Quincy-Massachusetts/BestX-AI-Engineer--Full-time-Internship--July---Dec-2026-_R-784548",
        "location": "Quincy, MA",
        "arrangement": "On-site",
        "salary": "$42–$65k",
        "posted": "today",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Collaborate with cross-functional teams to design AI and machine learning solutions for pre-trade and post-trade workflows. Develop secure applications and data-driven tools to enhance the BestX transaction cost analysis platform."
      },
      {
        "rank": 22,
        "score": 70,
        "title": "AI Automation & Agentic Systems Engineer",
        "company": "Monotype",
        "url": "https://monotype.wd1.myworkdayjobs.com/Monotype/job/Woburn-MA/AI-Automation---Agentic-Systems-Engineer_R0004775",
        "location": "Woburn, MA",
        "arrangement": "Hybrid",
        "salary": "$130–$155k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and implement AI-driven workflows and multi-agent automation systems to streamline enterprise business processes. Partner with cross-functional teams to translate operational requirements into scalable AI solutions using modern LLM platforms and orchestration tools."
      },
      {
        "rank": 23,
        "score": 70,
        "title": "Software Developer - Applied AI",
        "company": "Kimley-Horn",
        "url": "https://careers-kimley-horn.icims.com/jobs/24222/software-developer---applied-ai/job",
        "location": "Dallas, TX",
        "arrangement": "On-site",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop full-stack web applications and AI-powered features to streamline civil engineering workflows. This includes building RAG pipelines, multi-agent orchestration systems, and integrating AI capabilities into engineering data platforms."
      },
      {
        "rank": 24,
        "score": 69,
        "title": "Applied AI Engineer",
        "company": "Brightplan",
        "url": "https://jobs.workable.com/view/j9e2na7Qto8f5fHW3Uannz/remote-applied-ai-engineer-in-united-states-at-brightplan",
        "location": "United States",
        "arrangement": "Remote",
        "salary": "$125–$155k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and enhance AI-powered product features, specifically focusing on the AI Coach experience within a production SaaS platform. Develop Python-based services, refine prompts, and manage structured and vector data to deliver user-facing AI functionality."
      },
      {
        "rank": 25,
        "score": 69,
        "title": "Forward Deployed Product Engineer",
        "company": "Polymarket",
        "url": "https://jobs.ashbyhq.com/polymarket/8da10c0d-4624-43f3-bd6d-c0b11df74292",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Manage a portfolio of high-value clients from onboarding through retention while resolving technical issues. Translate client feedback and data into product insights to influence the engineering roadmap."
      },
      {
        "rank": 26,
        "score": 68,
        "title": "AI Engineer - GenAI",
        "company": "Dynasty Financial Partners, LLC",
        "url": "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3914729",
        "location": "St. Petersburg, FL",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, build, and operate production-grade AI systems including LLM-powered agents and RAG pipelines. Collaborate with cross-functional teams to automate business processes and establish performance evaluation frameworks."
      },
      {
        "rank": 27,
        "score": 68,
        "title": "Machine Learning Engineer",
        "company": "Robinhood",
        "url": "https://boards.greenhouse.io/robinhood/jobs/7960680?t=gh_src=&gh_jid=7960680",
        "location": "Bellevue, WA",
        "arrangement": "Hybrid",
        "salary": "$161–$200k",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Implement and evaluate machine learning algorithms focusing on advanced ranking, recommendation systems, and reinforcement learning. Collaborate cross-functionally to integrate these models into products and build reusable ML libraries."
      },
      {
        "rank": 28,
        "score": 66,
        "title": "Computer Vision AI & ML Engineer",
        "company": "Skild AI",
        "url": "https://job-boards.greenhouse.io/skildai-careers/jobs/5239930008",
        "location": "San Mateo, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy advanced perception systems for robotics, focusing on deep learning models for 3D scene understanding and object detection. Build scalable data pipelines and monitoring frameworks to integrate these models into real-time production systems."
      },
      {
        "rank": 29,
        "score": 66,
        "title": "ML Engineer",
        "company": "Mach9",
        "url": "https://jobs.ashbyhq.com/mach9/51061973-9726-4e8e-bba4-4bfa9e3ef004",
        "location": "San Francisco, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, train, and evaluate computer vision and 3D ML models to extract CAD-grade geometry from LiDAR and imagery. Manage the full model lifecycle from research prototyping to production integration within the Digital Surveyor software."
      },
      {
        "rank": 30,
        "score": 66,
        "title": "Systems Performance Engineer, Agentic AI Workloads – New College Grad 2026",
        "company": "NVIDIA",
        "url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/US-CA-Santa-Clara/Systems-Performance-Engineer--Agentic-AI-Workloads---New-College-Grad-2026_JR2018588",
        "location": "Santa Clara, CA / Durham, NC / +1",
        "arrangement": "On-site",
        "salary": "$124–$242k",
        "posted": "-1 days ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Develop and extend C++ and Python simulators to model system-level network and compute traffic for agentic AI workloads. Identify performance bottlenecks and provide architectural recommendations for next-generation datacenter and GPU systems."
      },
      {
        "rank": 31,
        "score": 66,
        "title": "AI Automation Specialist / Agentic Workflow Engineer",
        "company": "COFREIGHT INC",
        "url": "https://recruiting.paylocity.com/Recruiting/Jobs/Details/4200538",
        "location": "Buena Park, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy AI-powered agentic workflows and full-stack applications using local models and automation frameworks. Maintain production-ready systems while staying current with emerging AI tools and infrastructure operations."
      },
      {
        "rank": 32,
        "score": 66,
        "title": "Machine Learning Engineer, VLA",
        "company": "DiDi Labs",
        "url": "https://job-boards.greenhouse.io/didi/jobs/7975368",
        "location": "San Jose, CA",
        "arrangement": "On-site",
        "salary": "$129–$247k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and train large-scale deep learning foundation models for multi-agent trajectory prediction and autonomous vehicle planning. Develop scalable training pipelines and optimize models for on-vehicle deployment and real-world production systems."
      },
      {
        "rank": 33,
        "score": 65,
        "title": "Forward Deployed Engineer - New Verticals",
        "company": "Protege",
        "url": "https://jobs.ashbyhq.com/protege/b62ebf3e-e07f-4f67-bc9c-4787f23fe449",
        "location": "United States",
        "arrangement": "Remote",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build the technical foundation and reusable infrastructure for a new business vertical while leading early customer engagements from scoping to delivery. Partner with product and engineering teams to translate customer needs into core platform capabilities."
      },
      {
        "rank": 34,
        "score": 65,
        "title": "Forward Deployed Engineer",
        "company": "Gradial",
        "url": "https://job-boards.greenhouse.io/gradial/jobs/4245923009",
        "location": "Seattle, WA",
        "arrangement": "On-site",
        "salary": "$130–$210k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Lead technical discovery and full-stack implementation of AI platforms for enterprise customers to modernize content operations. Translate complex business workflows into scalable generative systems and collaborate with product teams to refine the core roadmap."
      },
      {
        "rank": 35,
        "score": 63,
        "title": "Research Engineer",
        "company": "Itron, Inc.",
        "url": "https://itron.wd5.myworkdayjobs.com/Itron/job/United-States-of-America-California-San-Jose/Research-Engineer_JR102276",
        "location": "San Jose, CA",
        "arrangement": "Hybrid",
        "salary": "$60–$115k",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The Research Engineer designs, develops, and validates distributed intelligence algorithms and applications for electric utility networks. This includes implementing grid simulation use cases and performing component troubleshooting within a laboratory environment."
      },
      {
        "rank": 36,
        "score": 62,
        "title": "AI Engineer",
        "company": "Abbott",
        "url": "https://abbott.wd5.myworkdayjobs.com/abbottcareers/job/United-States---Texas---Plano/AI-Engineer_31152145-1",
        "location": "Plano, TX",
        "arrangement": "On-site",
        "salary": "$51–$101k",
        "posted": "-1 days ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Integrate responsible AI principles into technological products and validate models for performance, fairness, and explainability. Ensure all AI development adheres to strict medical device regulatory standards and ethical frameworks."
      },
      {
        "rank": 37,
        "score": 62,
        "title": "Applied AI Engineer, Global Banking & Markets, New York City",
        "company": "Goldman Sachs",
        "url": "https://hdpc.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_3002/job/155460",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "$150–$225k",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy scalable AI models and agentic workflows to enhance revenue and operational efficiency within the equities business. Collaborate with stakeholders to integrate AI with quantitative finance and maintain production-ready software solutions."
      },
      {
        "rank": 38,
        "score": 61,
        "title": "Relocate to SF: Software Engineer (AI Infra)",
        "company": "Pylon",
        "url": "https://jobs.ashbyhq.com/pylon-labs/38ec5f57-31ed-471e-86eb-5e88a6269508",
        "location": "San Francisco, CA / Boulder, CO / +7",
        "arrangement": "On-site",
        "salary": "$180–$300k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and maintain platforms powering AI features, including prompt executions and search infrastructure. Improve LLM observability through AI evaluations and scorers to ensure quality and performance at scale."
      },
      {
        "rank": 39,
        "score": 61,
        "title": "Founding Engineer, Backend & Infra",
        "company": "Backbone Systems",
        "url": "https://jobs.ashbyhq.com/backbone/ba8c05b9-5553-4b47-bf89-ff841ba0d163",
        "location": "San Francisco, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and scale distributed systems and orchestration infrastructure to automate clinical and financial workflows in healthcare. Design reliable systems for processing messy healthcare data and implement observability and audit infrastructure for high-stakes production environmen"
      },
      {
        "rank": 40,
        "score": 61,
        "title": "Machine Learning Engineer, Motion Planning & Prediction",
        "company": "Avride",
        "url": "https://job-boards.greenhouse.io/avride/jobs/4013016009",
        "location": "Austin, TX",
        "arrangement": "On-site",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, train, and deploy machine learning models for behavioral prediction and motion planning. Develop data pipelines and collaborate with software engineers for real-time model integration."
      },
      {
        "rank": 41,
        "score": 60,
        "title": "Forward Deployed Software Engineer",
        "company": "Dirac, Inc.",
        "url": "https://job-boards.greenhouse.io/diracinc/jobs/4249650009?gh_jid=4249650009",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "$120–$200k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build integrations between BuildOS and customer systems while shipping deployment-critical features to remove technical blockers. Collaborate with customers and internal teams to drive product adoption and provide fast feedback through code reviews."
      },
      {
        "rank": 42,
        "score": 60,
        "title": "Applied AI Engineer",
        "company": "NobleReach Foundation",
        "url": "https://jobs.lever.co/noblereach/10259191-bf92-4b05-a05e-f1c6f1cd310d",
        "location": "Tysons, VA",
        "arrangement": "Hybrid",
        "salary": "$80–$95k",
        "posted": "-1 days ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "The Applied AI Engineer is responsible for the end-to-end development, deployment, and iteration of LLM-powered agents to automate internal business processes. This includes writing maintainable Python code, integrating third-party APIs, and collaborating with stakeholders to ens"
      },
      {
        "rank": 43,
        "score": 60,
        "title": "AI Engineer",
        "company": "Valley Bank",
        "url": "https://myjobs.adp.com/vnbcareers/cx/job-details?reqId=5001201444006",
        "location": "Saint Petersburg, FL / Morristown, NJ / +1",
        "arrangement": "On-site",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The role involves designing and maintaining AI-driven automation solutions and intelligent workflows using RPA platforms and AI agents. Responsibilities include developing Intelligent Document Processing solutions and collaborating with stakeholders to translate business requirem"
      },
      {
        "rank": 44,
        "score": 60,
        "title": "Machine Learning Engineer",
        "company": "Adobe",
        "url": "https://adobe.wd5.myworkdayjobs.com/external_experienced/job/San-Jose/Machine-Learning-Engineer_R169351",
        "location": "San Jose, CA",
        "arrangement": "On-site",
        "salary": "$126–$234k",
        "posted": "today",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Develop predictive models and scalable modeling algorithms on large-scale datasets to solve complex business problems. Collaborate with product management and engineering teams to build features for customer analytics and marketing optimization."
      },
      {
        "rank": 45,
        "score": 59,
        "title": "Software Engineer, Agentic Workflows",
        "company": "Apple",
        "url": "https://jobs.apple.com/en-us/details/200666134",
        "location": "Cupertino, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and build end-to-end software for agentic AI systems, developer tooling, and evaluation infrastructure for Siri. Collaborate with engineers and researchers to ship production systems running in the cloud."
      },
      {
        "rank": 46,
        "score": 58,
        "title": "Software Dev Engineer II, Secure Customer Content Storage and Analytics, AWS Applied AI Solution – Core Services",
        "company": "Amazon",
        "url": "https://www.amazon.jobs/en/jobs/10438214",
        "location": "Seattle, WA",
        "arrangement": "On-site",
        "salary": "$144–$194k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Own and deliver software features for event-based data storage systems and analytics platforms to support AI-powered business applications. Maintain and refactor existing services to improve performance, scalability, and security while mentoring team members through code reviews."
      },
      {
        "rank": 47,
        "score": 58,
        "title": "Software Research Engineer (ML)",
        "company": "Avride",
        "url": "https://job-boards.greenhouse.io/avride/jobs/4075884009",
        "location": "Austin, TX",
        "arrangement": "On-site",
        "salary": "",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The Research Engineer will design algorithms and tools for auto-labeling, data mining, and dataset monitoring to enhance data efficiency and model performance. They will collaborate with ML and Perception teams to integrate research results into production workflows."
      },
      {
        "rank": 48,
        "score": 58,
        "title": "Machine Learning Engineer",
        "company": "AllCloud",
        "url": "https://www.comeet.com/jobs/allcloud/71.008/machine-learning-engineer/8A.B60",
        "location": "New York, UN",
        "arrangement": "Remote",
        "salary": "",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and operate AWS-based infrastructure for data extraction, transformation, and loading to deliver predictive insights. Build and optimize complex data lakes and ML models to support customer data architecture and business needs."
      },
      {
        "rank": 49,
        "score": 57,
        "title": "ML Engineer, I - App Engine",
        "company": "Torc Robotics",
        "url": "https://job-boards.greenhouse.io/torcrobotics/jobs/8525554002",
        "location": "Ann Arbor, MI",
        "arrangement": "On-site",
        "salary": "$132–$159k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop a processing pipeline SDK for distributed systems and optimize resource usage for parallel execution of machine learning models. Create a runtime environment for virtual driver applications and provide high-quality code with comprehensive test cases."
      },
      {
        "rank": 50,
        "score": 57,
        "title": "Forward Deployed Engineer, Physics & Simulation",
        "company": "Periodic Labs",
        "url": "https://jobs.ashbyhq.com/periodic-labs/1bab7e17-20fd-4b82-a152-98b96375a626",
        "location": "Menlo Park, CA",
        "arrangement": "On-site",
        "salary": "$180–$250k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "available",
        "description": "Own the end-to-end simulation workflow for customer engagements, focusing on building and calibrating physics-based models for advanced manufacturing. Collaborate with internal ML teams to integrate simulation outputs with automated recipe generation and process optimization."
      },
      {
        "rank": 51,
        "score": 57,
        "title": "Machine Learning Engineer",
        "company": "Entravision",
        "url": "https://entravision.csod.com/ux/ats/careersite/1/home/requisition/5047?c=entravision",
        "location": "New York, UN",
        "arrangement": "On-site",
        "salary": "$140–$170k",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop and improve machine learning pipelines and deep neural network algorithms to solve complex business issues. Research, design, and deploy scalable data analytics solutions while collaborating with Tech and Ops teams."
      },
      {
        "rank": 52,
        "score": 57,
        "title": "AI Engineer",
        "company": "Ford Motor Company",
        "url": "https://efds.fa.em5.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/64340",
        "location": "Dearborn, MI",
        "arrangement": "Hybrid",
        "salary": "$100–$193k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The AI Engineer is responsible for delivering analytical, machine learning, and AI solutions to improve customer experience and business efficiency. This includes managing the full machine learning lifecycle from data preprocessing and feature engineering to model deployment."
      },
      {
        "rank": 53,
        "score": 55,
        "title": "AIML - ML Engineer, Responsible AI",
        "company": "Apple",
        "url": "https://jobs.apple.com/en-us/details/200642026",
        "location": "Seattle, WA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop models, tools, and metrics to evaluate the safety and robustness of generative AI models throughout their deployment lifecycle. Build human annotation and red teaming pipelines to interpret failures and assess risks in language and diffusion models."
      },
      {
        "rank": 54,
        "score": 55,
        "title": "Applied AI Engineer",
        "company": "QuoteWell",
        "url": "https://jobs.ashbyhq.com/quotewell/071cc0d9-6f69-4b65-af5d-f2b0e78307a1",
        "location": "Austin, TX",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Embed at retail insurance agencies to build and deploy governed AI workflows that systematize brokerage execution. Act as a conduit between customers and the internal product team to ensure the platform scales based on real-world field signals."
      },
      {
        "rank": 55,
        "score": 54,
        "title": "Forward Deployed Engineer",
        "company": "Namespace",
        "url": "https://jobs.ashbyhq.com/Namespace/a85700a7-1c51-4231-adc4-0b819132c3b3",
        "location": "San Francisco, CA",
        "arrangement": "Hybrid",
        "salary": "$150–$220k",
        "posted": "today",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Work directly with customer engineering teams to solve complex infrastructure and developer workflow challenges. Translate real-world customer challenges into product improvements and build tooling to increase developer productivity."
      },
      {
        "rank": 56,
        "score": 54,
        "title": "Machine Learning Engineer Video Processing Engineer",
        "company": "Apple",
        "url": "https://jobs.apple.com/en-us/details/200622819",
        "location": "Cupertino, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop and optimize machine learning-based video processing algorithms for Apple products. This includes researching state-of-the-art low-level vision methods and managing data curation for algorithm training."
      },
      {
        "rank": 57,
        "score": 53,
        "title": "Founding Engineer, Forward Deployed",
        "company": "Backbone Systems",
        "url": "https://jobs.ashbyhq.com/backbone/6900ff42-1dde-4fa5-9695-a7ecad7402eb",
        "location": "San Francisco, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The role involves collaborating with healthcare providers and payers to translate complex operational workflows into shipped software. You will identify customer pain points and build the clinical AI layer to automate healthcare payments."
      },
      {
        "rank": 58,
        "score": 52,
        "title": "Machine Learning Engineer III - FES",
        "company": "Fanatics Betting & Gaming",
        "url": "https://job-boards.greenhouse.io/fanaticsfbg/jobs/4252813009",
        "location": "New York, NY",
        "arrangement": "Remote",
        "salary": "$117–$167k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Own the end-to-end ML infrastructure for recommendation, personalization, and LTV scoring systems. Build and scale real-time and batch feature pipelines and model serving infrastructure across the Fanatics ecosystem."
      },
      {
        "rank": 59,
        "score": 51,
        "title": "AI Engineer III",
        "company": "Tulane University",
        "url": "https://tulane-ibqejb.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/1018",
        "location": "New Orleans, LA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The AI Engineer III manages the NebulaONE generative AI platform, overseeing administration, governance, and project design. The role coordinates with institutional stakeholders to ensure responsible AI adoption and scalable deployment across the university."
      },
      {
        "rank": 60,
        "score": 48,
        "title": "Research Engineer (Polymer Processing)",
        "company": "Ingenia Polymers Inc.",
        "url": "https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=d7aa1823-9e56-4664-af48-267adb84ff69&jobId=595141",
        "location": "Houston, TX",
        "arrangement": "On-site",
        "salary": "",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Lead the development and commercialization of new proprietary polymer products, specifically focusing on thermoplastic elastomers and functionalized polymers. Provide technical service support to customers and manage the scale-up process from laboratory trials to full production."
      },
      {
        "rank": 61,
        "score": 42,
        "title": "Relocate to SF: Software Engineer (AI Agents)",
        "company": "Pylon",
        "url": "https://jobs.ashbyhq.com/pylon-labs/bf160b39-8784-41e8-a712-88bd0283c6d8",
        "location": "San Francisco, CA / Boulder, CO / +7",
        "arrangement": "On-site",
        "salary": "$180–$300k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and rapidly iterate on the next set of AI features for Pylon's B2B post-sales support platform. Focus on improving the quality and performance of AI features based on customer feedback."
      },
      {
        "rank": 62,
        "score": 35,
        "title": "Food Research Engineer",
        "company": "JBT Marel",
        "url": "https://jbtm.wd108.myworkdayjobs.com/JBT_Marel_Career_Site/job/US---Lakeland-FL/Research-Engineer_21242",
        "location": "Lakeland, FL",
        "arrangement": "On-site",
        "salary": "$80–$85k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The Research Engineer will provide technical and research assistance for thermal processing of hermetically sealed containers to support sales and machinery installations. Responsibilities include conducting laboratory and field studies, managing FDA filings, and performing elect"
      },
      {
        "rank": 63,
        "score": 33,
        "title": "Research Engineer 2 - Hardware and Software Design (Temporary)",
        "company": "University of Washington",
        "url": "https://uw.wd5.myworkdayjobs.com/UWHires/job/Seattle-WA/Research-Engineer-2---Hardware-and-Software-Design--Temporary-_REQ-0000133109",
        "location": "Seattle, WA",
        "arrangement": "On-site",
        "salary": "$69–$84k",
        "posted": "-1 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and fabricate in vitro fluidics hardware and analytical instrumentation using CAD and 3D printing. Develop software for the computer-control and automation of these systems to assess real-time tissue function."
      }
    ]
  },
  {
    "id": "2026-06-02_10d",
    "date": "2026-06-02",
    "window": "10d",
    "crawled": 100,
    "survived": 50,
    "drop_log": {
      "title-too-senior": 18,
      "citizenship/clearance": 6,
      "yoe>=4-required": 5,
      "no-sponsorship": 7,
      "no-sponsorship-ai+text": 5,
      "duplicate-in-run": 7,
      "defense-employer": 1,
      "non-US": 1
    },
    "source": "apify:fantastic-jobs/career-site-job-listing-api",
    "jobs": [
      {
        "rank": 1,
        "score": 91,
        "title": "Software AI Engineer Mid-Level, Context Engineering",
        "company": "WEX",
        "url": "https://wexinc.wd5.myworkdayjobs.com/WEXInc/job/US---Remote/Software-AI-Engineer-Mid-Level---Context-Engineering_R21596-1",
        "location": "California, MD",
        "arrangement": "Remote",
        "salary": "$125–$149k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop and maintain the core software components of the AI Context Layer to connect enterprise data to LLMs. This includes building AI Data Lakehouse services, automating CI/CD pipelines, and implementing RAG patterns for secure data retrieval."
      },
      {
        "rank": 2,
        "score": 86,
        "title": "I Software Engineer – Agentic AI System",
        "company": "Intel Corporation",
        "url": "https://intel.wd1.myworkdayjobs.com/External/job/US-California-Santa-Clara/I-Software-Engineer---Agentic-AI-System-_JR0282814",
        "location": "Folsom, CA / Santa Clara, CA / +2",
        "arrangement": "Hybrid",
        "salary": "$150–$211k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and maintain scalable deployment and orchestration systems for agentic AI frameworks and evaluation ecosystems. Develop data pipelines, observability tooling, and automated pipelines for performance and reliability detection."
      },
      {
        "rank": 3,
        "score": 85,
        "title": "AI Engineer",
        "company": "Illumina",
        "url": "https://illumina.wd1.myworkdayjobs.com/illumina-careers/job/US---California---San-Diego/AI-Engineer_42963-JOB-1",
        "location": "San Diego, CA",
        "arrangement": "On-site",
        "salary": "$82–$124k",
        "posted": "1 day ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Implement production AI features including LLM integrations, RAG pipelines, and backend services. Evaluate model performance and collaborate with cross-functional teams to solve real user problems."
      },
      {
        "rank": 4,
        "score": 81,
        "title": "AI Engineer",
        "company": "Portless",
        "url": "https://jobs.workable.com/view/boRuEDWWy88rZ2DjiiwZy1/remote-ai-engineer-in-united-states-at-portless",
        "location": "United States",
        "arrangement": "Remote",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy AI-powered systems, including LLM integrations and agentic workflows, to optimize B2B portals and internal tooling. Collaborate cross-functionally to translate business problems into scalable AI solutions while monitoring performance and reliability."
      },
      {
        "rank": 5,
        "score": 80,
        "title": "Software Engineer, Agentic AI",
        "company": "Displai",
        "url": "https://jobs.ashbyhq.com/displai/14171ec3-2ba9-4e54-9a06-80b63855d4be",
        "location": "United States",
        "arrangement": "Hybrid",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and implement agentic AI features and LLM-powered workflows into the Displai CMS. Own features end-to-end from prototyping and backend API development to frontend UI and production rollout."
      },
      {
        "rank": 6,
        "score": 76,
        "title": "AI Engineer",
        "company": "RA Capital Management, LLC",
        "url": "https://job-boards.greenhouse.io/racapitalmanagementllc/jobs/4563736008",
        "location": "Boston, MA",
        "arrangement": "Hybrid",
        "salary": "$120–$180k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and develop end-to-end AI applications and deep learning models to identify and evaluate biomedical investment opportunities. Build and optimize large language models and real-time prediction systems using proprietary research data."
      },
      {
        "rank": 7,
        "score": 75,
        "title": "AI Engineer",
        "company": "GE Vernova",
        "url": "https://gevernova.wd5.myworkdayjobs.com/Vernova_ExternalSite/job/Bellevue-WA-US/AI-Engineer_R5041190",
        "location": "Bellevue, WA",
        "arrangement": "On-site",
        "salary": "$109–$163k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop and deploy AI-driven systems and backend services to enable intelligent automation for grid applications. Support the creation of LLM-based applications, AI agent frameworks, and data pipelines for real-time grid data processing."
      },
      {
        "rank": 8,
        "score": 75,
        "title": "AI Engineer",
        "company": "Quantifi",
        "url": "https://quantifisolutions.freshteam.com/jobs/_BdrQBi1EkVS/copy-of-ai-engineer",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "$180–$200k",
        "posted": "3 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "As the first AI Engineer, you will architect, build, and deploy core systems for Quantifi’s AI foundation. You will own the full lifecycle of AI-powered agents and workflows, leading the evolution of the agent orchestration layer."
      },
      {
        "rank": 9,
        "score": 74,
        "title": "AI Engineer Associate",
        "company": "SAIC",
        "url": "https://eihu.fa.us8.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX/job/2612236",
        "location": "Largo, MD",
        "arrangement": "Hybrid",
        "salary": "",
        "posted": "1 day ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Deploy, configure, and maintain machine learning and large language models on GPU-enabled on-premises and cloud infrastructure. Design secure data pipelines and develop agentic AI pipelines to improve government operational use-cases."
      },
      {
        "rank": 10,
        "score": 74,
        "title": "Machine Learning Engineer - Generative AI",
        "company": "Qualcomm",
        "url": "https://careers.qualcomm.com/careers/job/446718055384-machine-learning-engineer-generative-ai-san-diego-california-united-states-of-america",
        "location": "San Diego, CA",
        "arrangement": "On-site",
        "salary": "$128–$192k",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy generative AI solutions focusing on LLMs, RAG, and intelligent agent systems. Develop fine-tuning strategies and evaluation frameworks to improve model performance and autonomous AI workflows."
      },
      {
        "rank": 11,
        "score": 73,
        "title": "Machine Learning Engineer",
        "company": "Multi Media LLC",
        "url": "https://jobs.workable.com/view/bqkqSAJN2W35yHL1WmQ5C9/remote-machine-learning-engineer-in-united-states-at-multi-media-llc",
        "location": "United States",
        "arrangement": "Remote",
        "salary": "$180–$200k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and maintain production-grade machine learning systems for search, recommendations, and personalization on a global-scale platform. Collaborate with cross-functional teams to translate business needs into scalable ML solutions that improve user engagement and discovery."
      },
      {
        "rank": 12,
        "score": 73,
        "title": "Open-Source Machine Learning Engineer - US Remote",
        "company": "Hugging Face",
        "url": "https://jobs.workable.com/view/8UbCFFqNjvdNUKZBYdFAMR/open-source-machine-learning-engineer---us-remote-in-new-york-at-hugging-face",
        "location": "New York, NY",
        "arrangement": "Remote",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Improve the open-source machine learning ecosystem by developing and maintaining libraries like Transformers, Datasets, and PyTorch. Collaborate with a global community of researchers and practitioners via GitHub, forums, and Slack to foster tool adoption."
      },
      {
        "rank": 13,
        "score": 67,
        "title": "Machine Learning Engineer",
        "company": "Adobe",
        "url": "https://careers.adobe.com/us/en/job/R163760/Machine-Learning-Engineer",
        "location": "San Jose, CA",
        "arrangement": "On-site",
        "salary": "$126–$234k",
        "posted": "3 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop and deploy predictive and generative ML models to optimize customer experience orchestration and autonomous agents. Implement ML-Ops best practices and collaborate with research teams to integrate models into production operations."
      },
      {
        "rank": 14,
        "score": 66,
        "title": "Machine Learning Engineer, VLA",
        "company": "DiDi Labs",
        "url": "https://job-boards.greenhouse.io/didi/jobs/7975368",
        "location": "San Jose, CA",
        "arrangement": "On-site",
        "salary": "$129–$247k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and train large-scale deep learning foundation models for multi-agent trajectory prediction and autonomous vehicle planning. Develop scalable training pipelines and optimize models for on-vehicle deployment and real-world production systems."
      },
      {
        "rank": 15,
        "score": 66,
        "title": "AI Engineer - Developer Productivity",
        "company": "Hewlett Packard Enterprise",
        "url": "https://hpe.wd5.myworkdayjobs.com/acjobsite/job/Spring-Texas-United-States-of-America/AI-Engineer---Developer-Productivity_1207650",
        "location": "Fort Collins, CO / Spring, TX",
        "arrangement": "Hybrid",
        "salary": "$120–$276k",
        "posted": "2 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Partner with engineering teams to execute AI productivity initiatives and embed within workflows to identify improvement opportunities. Build AI personas, automate developer workflows, and prototype tools in Python to enhance coding efficiency."
      },
      {
        "rank": 16,
        "score": 66,
        "title": "AI Engineer – Model Operations & Enablement Team",
        "company": "Principal Financial Group",
        "url": "https://careers.principal.com/careers-home/jobs/51113",
        "location": "Des Moines, IA",
        "arrangement": "Remote",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and scale scalable machine learning and generative AI solutions with a focus on reliability, monitoring, and quality. Build CI/CD pipelines and develop reusable frameworks to enable enterprise-wide AI adoption and observability."
      },
      {
        "rank": 17,
        "score": 66,
        "title": "AI Engineer Associate",
        "company": "Volkswagen AG",
        "url": "https://jobs.volkswagen-group.com/Volkswagen-Group/job/Belmont-AI-Engineer-Associate-CA-94002/1398883833/",
        "location": "Belmont, CA",
        "arrangement": "On-site",
        "salary": "$120–$135k",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The role involves designing and implementing machine learning modules for autonomous driving and automotive applications. Responsibilities include software development, testing in prototypes, and creating technical documentation."
      },
      {
        "rank": 18,
        "score": 65,
        "title": "Forward Deployed Engineer",
        "company": "Gradial",
        "url": "https://job-boards.greenhouse.io/gradial/jobs/4245923009",
        "location": "Seattle, WA",
        "arrangement": "On-site",
        "salary": "$130–$210k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Lead technical discovery and full-stack implementation of AI platforms for enterprise customers to modernize content operations. Translate complex business workflows into scalable generative systems and collaborate with product teams to refine the core roadmap."
      },
      {
        "rank": 19,
        "score": 64,
        "title": "Machine Learning Engineer II",
        "company": "Lessen",
        "url": "https://jobs.lever.co/lessen/7e37348a-54fc-4e5b-942d-216a0673f7dc",
        "location": "Chicago, IL",
        "arrangement": "Hybrid",
        "salary": "",
        "posted": "3 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, deploy, and fine-tune large language models to automate processes and solve business problems. Collaborate cross-functionally to build scalable AI/ML solutions such as copilot systems and intelligent voice assistants."
      },
      {
        "rank": 20,
        "score": 64,
        "title": "AI Engineer",
        "company": "SageNet",
        "url": "https://recruiting2.ultipro.com/SAG1001SGN/JobBoard/e49f53d0-1675-480b-b3bb-4d6dac298bc3/OpportunityDetail?opportunityId=946ae28c-c825-461c-a4b2-2c724b402db0",
        "location": "Tulsa, OK",
        "arrangement": "Hybrid",
        "salary": "$95–$120k",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop and deploy AI models and algorithms to improve operational efficiency and enhance customer experiences within managed services environments. Collaborate with automation engineers to integrate AI solutions into existing enterprise systems and scalable workflows."
      },
      {
        "rank": 21,
        "score": 63,
        "title": "AI Research Engineer, Pre-training",
        "company": "Hudson River Trading",
        "url": "https://www.hudsonrivertrading.com/careers/job/?gh_jid=7972584",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "$250–$300k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Improve all aspects of large-scale model training, including kernel development, data loading, and fault-tolerance. Collaborate with researchers to co-design foundation models for financial markets and shape the research agenda."
      },
      {
        "rank": 22,
        "score": 63,
        "title": "AI Research Engineer, Inference",
        "company": "Hudson River Trading",
        "url": "https://www.hudsonrivertrading.com/careers/job/?gh_jid=7972593",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "$250–$300k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Improve all aspects of large-scale model inference, including GPU kernel development and the use of ASICs and FPGAs. Collaborate with researchers to co-design models and shape the research agenda for foundation models for markets."
      },
      {
        "rank": 23,
        "score": 63,
        "title": "Forward Deployed Engineer",
        "company": "Teleskope",
        "url": "https://jobs.ashbyhq.com/teleskope/278bce22-653b-41f1-aaeb-2c2f7c7f4092",
        "location": "New York, NY",
        "arrangement": "Hybrid",
        "salary": "$130–$170k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Act as the primary technical resource for enterprise customers, bridging the gap between Go-to-Market and Engineering teams. Responsibilities include building custom integrations, diagnosing customer-specific bugs, and influencing the product roadmap based on customer feedback."
      },
      {
        "rank": 24,
        "score": 63,
        "title": "Applied AI Engineer",
        "company": "WS Development",
        "url": "https://jobs.workable.com/view/5MxDZf1Jn86Ykwcuov7AYi/applied-ai-engineer-in-chestnut-hill-at-ws-development",
        "location": "Newton, MA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy end-to-end AI solutions and agentic systems to automate business workflows across various departments. Build internal AI applications and establish evaluation pipelines to ensure reliability, performance, and responsible AI governance."
      },
      {
        "rank": 25,
        "score": 63,
        "title": "AI Engineer, Model Quality and Performance",
        "company": "Cerebras Systems",
        "url": "https://job-boards.greenhouse.io/cerebrassystems/jobs/7735288003",
        "location": "Sunnyvale, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Own model quality and performance for inference offerings by designing AI-driven evaluation suites and benchmarking workflows. Build automated pipelines to measure model quality at scale and synthesize performance data into user-friendly tooling."
      },
      {
        "rank": 26,
        "score": 63,
        "title": "ML Engineer, Network Intelligence",
        "company": "Colt Technology Services",
        "url": "https://joblistings.colt.net/job/ML-Engineer%2C-Network-Intelligence/1398817233/",
        "location": "United States",
        "arrangement": "Hybrid",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop and operationalize classical ML models for anomaly detection, predictive maintenance, and traffic forecasting using network telemetry data. Build the data pipeline and feature engineering layer in GCP BigQuery to support the AI WAN closed-loop architecture."
      },
      {
        "rank": 27,
        "score": 62,
        "title": "Machine Learning Engineer, Level 4",
        "company": "Snap Inc.",
        "url": "https://wd1.myworkdaysite.com/recruiting/snapchat/sourced/job/Palo-Alto-California/Machine-Learning-Engineer--Level-4_Q226SWEML3-1",
        "location": "Los Angeles, CA / Palo Alto, CA / +3",
        "arrangement": "Hybrid",
        "salary": "$147–$259k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Build and deploy scalable machine learning models to power core products for millions of users. Own the full ML lifecycle from initial data analysis to production deployment and cross-functional prototyping."
      },
      {
        "rank": 28,
        "score": 62,
        "title": "AI Automation Specialist / Agentic Workflow Engineer",
        "company": "COFREIGHT INC",
        "url": "https://recruiting.paylocity.com/Recruiting/Jobs/Details/4200538",
        "location": "Buena Park, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy AI-powered agentic workflows and full-stack applications using local models and automation frameworks. Maintain production-ready systems while staying current with emerging AI tools and infrastructure operations."
      },
      {
        "rank": 29,
        "score": 61,
        "title": "Forward Deployed Software Engineer",
        "company": "PVM, Inc.",
        "url": "https://job-boards.greenhouse.io/pvminc/jobs/5150317007",
        "location": "Huntsville, AL",
        "arrangement": "On-site",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The role involves developing and delivering Palantir capabilities, including analytical dashboards and AI-enabled features, within an agile environment. The engineer will handle data integration, ontology engineering, and production hardening to ensure mission-aligned capabilitie"
      },
      {
        "rank": 30,
        "score": 61,
        "title": "Forward Deployed Engineer, Tavily",
        "company": "Nebius",
        "url": "https://careers.nebius.com/?gh_jid=4825218101",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "$140–$200k",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, prototype, and deploy integrations of Tavily's API into real-world agentic systems for strategic partners. Bridge the gap between product, engineering, and sales to build production-grade RAG pipelines and GenAI use cases."
      },
      {
        "rank": 31,
        "score": 61,
        "title": "Forward Deployed Engineer",
        "company": "PVM Inc",
        "url": "https://pvm.bamboohr.com/careers/158",
        "location": "Mooresville, AL",
        "arrangement": "On-site",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The Forward Deployed Engineer will develop and deliver Palantir capabilities, including analytical dashboards and AI-enabled features. They will manage data integration, ontology engineering, and CI/CD pipeline tasks within an agile environment."
      },
      {
        "rank": 32,
        "score": 60,
        "title": "Forward Deployed Engineer",
        "company": "Bobyard",
        "url": "https://jobs.ashbyhq.com/bobyard/39196a79-10f7-4c8e-9b40-d77134734e87",
        "location": "San Francisco, CA",
        "arrangement": "On-site",
        "salary": "$120–$150k",
        "posted": "2 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Embed with strategic general contractor customers to identify critical problems and ship full-stack solutions directly in their environments. Bridge the gap between customer needs and the product roadmap by converting one-off solutions into scalable platform capabilities."
      },
      {
        "rank": 33,
        "score": 59,
        "title": "Applied AI Engineer",
        "company": "Eagle",
        "url": "https://jobs.ashbyhq.com/eagle/ddd07f46-a42a-4709-8e19-091d5145a9e7",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "$150–$300k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The role involves embedding with engineering firms to discover problems and building AI-powered tools to automate engineering workflows. You will own the end-to-end process from discovery to deployment while collaborating with the CTO on technical direction."
      },
      {
        "rank": 34,
        "score": 58,
        "title": "Machine Learning Engineer",
        "company": "AllCloud",
        "url": "https://www.comeet.com/jobs/allcloud/71.008/machine-learning-engineer/8A.B60",
        "location": "New York, UN",
        "arrangement": "Remote",
        "salary": "",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and operate AWS-based infrastructure for data extraction, transformation, and loading to deliver predictive insights. Build and optimize complex data lakes and ML models to support customer data architecture and business needs."
      },
      {
        "rank": 35,
        "score": 58,
        "title": "Applied AI Engineer",
        "company": "Abbott Laboratories",
        "url": "https://www.jobs.abbott/us/en/job/31151736/Applied-AI-Engineer",
        "location": "Lewes, DE",
        "arrangement": "Remote",
        "salary": "$61–$123k",
        "posted": "1 day ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "The role involves developing and implementing AI-powered systems and platforms to address business use cases. Key tasks include working with large language models, monitoring model performance, and deploying models to cloud platforms."
      },
      {
        "rank": 36,
        "score": 58,
        "title": "Applied AI Engineer",
        "company": "Abbott",
        "url": "https://abbott.wd5.myworkdayjobs.com/abbottcareers/job/United-States---Illinois---Abbott-Park/Applied-AI-Engineer_31151736-1",
        "location": "United States",
        "arrangement": "Remote",
        "salary": "$61–$123k",
        "posted": "1 day ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Develop and implement AI-powered systems and platforms to address business use cases, specifically focusing on large language models. Collaborate with cross-functional teams to deploy models to cloud platforms and monitor performance."
      },
      {
        "rank": 37,
        "score": 58,
        "title": "Forward Deployed Robotics Engineer",
        "company": "Mecka",
        "url": "https://jobs.ashbyhq.com/mecka.ai/a2fb71b6-bb8e-4d7c-9f87-f537aa6b2114",
        "location": "New York, NY",
        "arrangement": "On-site",
        "salary": "$120–$180k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The role involves managing on-site robot deployments, ensuring proper setup, and troubleshooting hardware and software issues in real-time. Additionally, the engineer leads data capture operations and supports teleoperation workflows to ensure high-quality data for AI training."
      },
      {
        "rank": 38,
        "score": 58,
        "title": "AI Engineer",
        "company": "Kanu AI",
        "url": "https://jobs.gem.com/kanu-ai/am9icG9zdDo01b7TB2rXJMU1Dz9CUbUP",
        "location": "Seattle, WA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "available",
        "description": "Design and maintain full-stack features including backend APIs, LLM integrations, and cloud automation. Collaborate with product and GTM teams to ship secure, scalable, and enterprise-ready AI solutions."
      },
      {
        "rank": 39,
        "score": 57,
        "title": "AI Engineer",
        "company": "Ford Motor Company",
        "url": "https://efds.fa.em5.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/64340",
        "location": "Dearborn, MI",
        "arrangement": "Hybrid",
        "salary": "$100–$193k",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "The AI Engineer is responsible for delivering analytical, machine learning, and AI solutions to improve customer experience and business efficiency. This includes managing the full machine learning lifecycle from data preprocessing and feature engineering to model deployment."
      },
      {
        "rank": 40,
        "score": 57,
        "title": "Associate GTM AI Engineer",
        "company": "Anaplan",
        "url": "https://job-boards.greenhouse.io/anaplan/jobs/8538805002",
        "location": "San Francisco, CA",
        "arrangement": "On-site",
        "salary": "$83–$112k",
        "posted": "4 days ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "The role focuses on designing and deploying AI workflows and agents to automate manual tasks for Sales, Marketing, and Customer Success teams. You will manage the intake of AI use cases and drive adoption through documentation and enablement."
      },
      {
        "rank": 41,
        "score": 57,
        "title": "Acceleration Center- Agentic AI and Machine Learning Developer- Experienced Associate",
        "company": "PwC",
        "url": "https://pwc.wd3.myworkdayjobs.com/US_Experienced_Careers/job/NY-New-York/Risk-Architecture--Agentic-AI-and-Machine-Learning-Developer--Experienced-Associate_731539WD",
        "location": "Tampa, FL / Chicago, IL / +3",
        "arrangement": "On-site",
        "salary": "$61–$100k",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and deploy scalable AI and machine learning solutions to transform raw data into actionable business insights. Collaborate with teams to integrate AI systems into existing data infrastructure and maintain robust data pipelines."
      },
      {
        "rank": 42,
        "score": 55,
        "title": "Machine Learning Engineer - Semantic Reasoning (Highway)",
        "company": "Zoox",
        "url": "https://jobs.lever.co/zoox/2bfdc02e-41f1-40f2-a748-4aaae3831d21",
        "location": "Foster City, CA / Boston, MA",
        "arrangement": "Hybrid",
        "salary": "$189–$258k",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design, train, and deploy deep learning models for semantic reasoning to enable autonomous vehicles to navigate high-speed highway environments. Collaborate cross-functionally to optimize models for real-time inference and resolve perception-related edge cases."
      },
      {
        "rank": 43,
        "score": 55,
        "title": "AI Engineer - Operations",
        "company": "Deposco",
        "url": "https://jobs.ashbyhq.com/deposco/0d3c955b-3fbb-43a1-9e6e-bf04b6ef1b3f",
        "location": "Alpharetta, GA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Lead the internal application of AI and LLMs to automate operations and increase productivity across the organization. Develop AI-enabled utilities and internal tools while collaborating cross-functionally to identify high-impact automation opportunities."
      },
      {
        "rank": 44,
        "score": 54,
        "title": "Machine Learning Engineer Video Processing Engineer",
        "company": "Apple",
        "url": "https://jobs.apple.com/en-us/details/200622819",
        "location": "Cupertino, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop and optimize machine learning-based video processing algorithms for Apple products. This includes researching state-of-the-art low-level vision methods and managing data curation for algorithm training."
      },
      {
        "rank": 45,
        "score": 54,
        "title": "Research Engineer",
        "company": "Autodesk",
        "url": "https://autodesk.wd1.myworkdayjobs.com/Ext/job/San-Francisco-CA-USA/Research-Engineer_26WD97948",
        "location": "San Francisco, CA",
        "arrangement": "On-site",
        "salary": "$122–$219k",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Design and execute hands-on experiments to advance manufacturing processes using AI, robotics, and digital twins. Develop integrated software and hardware pipelines to translate research insights into scalable technologies and intellectual property."
      },
      {
        "rank": 46,
        "score": 51,
        "title": "R&D Software Engineer, AI & Computational Platforms",
        "company": "Smith+Nephew",
        "url": "https://smithnephew.wd5.myworkdayjobs.com/External/job/Pittsburgh-PA/R-D-Software-Engineer--AI---Computational-Platforms_R90814",
        "location": "Pittsburgh, PA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "2 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Develop and scale software solutions, APIs, and technical workflows to support AI, computational modeling, and simulation projects. Collaborate with multidisciplinary teams to implement strong software engineering practices and integrate research outputs into usable applications."
      },
      {
        "rank": 47,
        "score": 49,
        "title": "Forward Deployed Engineer",
        "company": "Namespace",
        "url": "https://jobs.ashbyhq.com/Namespace/da8147a0-17aa-4a0b-8778-03d077257ec3",
        "location": "San Francisco, CA",
        "arrangement": "Hybrid",
        "salary": "$150–$220k",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Work directly with customers to debug complex infrastructure issues and optimize developer workflows. Translate customer pain points into product features and platform improvements to reduce operational friction."
      },
      {
        "rank": 48,
        "score": 48,
        "title": "Machine Learning Video Research Engineer",
        "company": "Apple",
        "url": "https://jobs.apple.com/en-us/details/200665879",
        "location": "Cupertino, CA",
        "arrangement": "On-site",
        "salary": "",
        "posted": "1 day ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Research and develop practical ML-based video algorithms to build the next generation of video technology for Apple products. Collaborate with colleagues to solve challenging problems at the frontier of deep learning and compression research."
      },
      {
        "rank": 49,
        "score": 41,
        "title": "Entry-Level Software Engineer — AI Research",
        "company": "Tokyo Electron",
        "url": "https://tel.wd3.myworkdayjobs.com/TEL-Careers/job/San-Jose/Entry-Level-Software-Engineer---AI-Research_R26-00785",
        "location": "San Jose, CA",
        "arrangement": "Hybrid",
        "salary": "",
        "posted": "1 day ago",
        "experience": "0-2",
        "sponsorship": "unknown",
        "description": "Drive the development of AI research tasks and convert theoretical ideas into productive code. Participate in system testing, field trials, and the debugging of integrated hardware/software prototypes."
      },
      {
        "rank": 50,
        "score": 41,
        "title": "Forward Deployed Engineer",
        "company": "Attio",
        "url": "https://jobs.ashbyhq.com/attio/26c31052-b667-46ae-b459-049018e55e96",
        "location": "San Francisco, CA",
        "arrangement": "Hybrid",
        "salary": "$130–$170k",
        "posted": "4 days ago",
        "experience": "2-5",
        "sponsorship": "unknown",
        "description": "Architect and deploy best-in-class GTM stacks for high-value customers using Attio as the core. Build custom API integrations and no-code automations while providing technical insights to the product team to shape the roadmap."
      }
    ]
  }
];
