window.HIRE_SESSIONS = [
  {
    "id": "2026-06-04_us-ai",
    "date": "2026-06-04",
    "label": "us-ai",
    "raw_total": 50,
    "after_dedup": 24,
    "drop_log": {
      "already-seen": 0,
      "duplicate-in-run": 0,
      "filtered-niche": 1,
      "post-too-old": 25,
      "post-no-date": 0
    },
    "people": [
      {
        "kind": "recruiter",
        "name": "Aaron White",
        "title": "Senior Technical Recruiter",
        "company": "Scale AI",
        "linkedin_url": "https://www.linkedin.com/in/aaronwhite143",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Aaron White. Senior Technical Recruiter at Scale AI. University of Oregon. United States.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "830a8a5f464f646f",
        "score": 70,
        "company_in_jobs": false,
        "rank": 1
      },
      {
        "kind": "recruiter",
        "name": "Mike Rubino",
        "title": "Head of Talent",
        "company": "AI Fund (Andrew Ng's Venture Studio)",
        "linkedin_url": "https://www.linkedin.com/in/mikerubino-ai-fund",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Head of Talent @ AI Fund, Andrew Ng's Venture Studio. Hiring Technical talent across portfolio companies.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:31.615Z",
        "_id": "1f45a4e6a137b345",
        "score": 69,
        "company_in_jobs": false,
        "rank": 2
      },
      {
        "kind": "recruiter",
        "name": "Ivory Mcgilvery",
        "title": "Senior Technical Recruiter | AI, Data",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/ivorymcgilvery",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Open to roles focused on AI & Data Talent Acquisition. Contract or Full-Time, Remote. Previously SpyCloud.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:26.920Z",
        "_id": "b0b0ecc253e3c55d",
        "score": 67,
        "company_in_jobs": false,
        "rank": 3
      },
      {
        "kind": "recruiter",
        "name": "Ravi Kumar D",
        "title": "Strategic AI Recruiter",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/ravdatla",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Strategic AI Recruiter — Hiring AI talent, Seed-to-IPO teams. ML Engineers, GenAI Researchers, LLM specialists.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:26.920Z",
        "_id": "75fae5544082f75d",
        "score": 63,
        "company_in_jobs": false,
        "rank": 4
      },
      {
        "kind": "recruiter",
        "name": "Morgan Coovert",
        "title": "Founding Recruiter",
        "company": "David AI",
        "linkedin_url": "https://www.linkedin.com/in/morgancoovert",
        "post_url": null,
        "location": "David AI. Austin, Texas, United States",
        "hiring_for": null,
        "context": "Founding Recruiter @ David AI. Austin, Texas, United States. Previously LAZ Parking.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:31.615Z",
        "_id": "23d4135704bd92b8",
        "score": 61,
        "company_in_jobs": false,
        "rank": 5
      },
      {
        "kind": "recruiter",
        "name": "Danny Levy",
        "title": "Senior Technical Recruiter",
        "company": "Google Cloud AI",
        "linkedin_url": "https://www.linkedin.com/in/imdannydope",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Senior Technical Recruiter @ Google Cloud AI. Florida State. Previously Lead Engineering Recruiter at Nest.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:26.920Z",
        "_id": "ed8fb8cb474ba17a",
        "score": 58,
        "company_in_jobs": false,
        "rank": 6
      },
      {
        "kind": "recruiter",
        "name": "Adam Solomon",
        "title": "Senior Technical Talent Acquisition Recruiter",
        "company": "Jorie AI",
        "linkedin_url": "https://www.linkedin.com/in/adamleesolomon",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Adam Solomon. Senior Technical Talent Acquisition Recruiter. Jorie AI. Vienna, Virginia.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:31.615Z",
        "_id": "5229c8a523f32f0e",
        "score": 58,
        "company_in_jobs": false,
        "rank": 7
      },
      {
        "kind": "recruiter",
        "name": "Shawn Flood",
        "title": "Head of Talent",
        "company": "Unconventional AI",
        "linkedin_url": "https://www.linkedin.com/in/shawnflood",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Head of Talent at Unconventional AI — Building world-class teams for AI companies. Previously Principal Technical Recruiter.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "9600eb42330b9fa3",
        "score": 57,
        "company_in_jobs": false,
        "rank": 8
      },
      {
        "kind": "recruiter",
        "name": "Michael Goldman",
        "title": "VP, Head of Talent Acquisition",
        "company": "FLOWX.AI",
        "linkedin_url": "https://www.linkedin.com/in/mikegoldman1",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "VP, Head of Talent Acquisition. FLOWX.AI. Sep 2023 - Feb 2025. New York. Reporting to CEO, hired as ...",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "9903529f0a5e7495",
        "score": 57,
        "company_in_jobs": false,
        "rank": 9
      },
      {
        "kind": "recruiter",
        "name": "Harp Dhanota",
        "title": "Head of Talent Acquisition",
        "company": "C3 AI",
        "linkedin_url": "https://www.linkedin.com/in/harpsdhanota",
        "post_url": null,
        "location": "San Francisco, California, United States",
        "hiring_for": null,
        "context": "Head of Talent Acquisition @ C3 AI (NYSE: AI). San Francisco, California, United States. Previously Technical Recruiter at Vivo Inc.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "40acbe48e748cfdf",
        "score": 57,
        "company_in_jobs": false,
        "rank": 10
      },
      {
        "kind": "recruiter",
        "name": "Trenton Fitzhugh",
        "title": "Senior Technical ML/AI Recruiter",
        "company": "Netflix",
        "linkedin_url": "https://www.linkedin.com/in/trentonfitzhugh",
        "post_url": null,
        "location": "Mentor. Netflix. San Jose, California, United States",
        "hiring_for": null,
        "context": "Senior Technical ML/AI Recruiter, Leader, and Mentor. Netflix. San Jose, California, United States. Senior ML/AI ...",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "d78ae651b72a0af5",
        "score": 55,
        "company_in_jobs": false,
        "rank": 11
      },
      {
        "kind": "recruiter",
        "name": "Tim C.",
        "title": "Staff Technical Recruiter, AI SW & HW Engineering",
        "company": "Tesla",
        "linkedin_url": "https://www.linkedin.com/in/teslatim",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Staff Technical Recruiter, AI SW & HW Engineering at Tesla.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "c9f84ba0fece41d3",
        "score": 55,
        "company_in_jobs": false,
        "rank": 12
      },
      {
        "kind": "recruiter",
        "name": "Magda Melena",
        "title": "Senior Technical Recruiter",
        "company": "Marvell Technology",
        "linkedin_url": "https://www.linkedin.com/in/magdamelena",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Senior Technical Recruiter @ Marvell Technology — Hardware Recruiting, AI Infrastructure.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "59d6ad5f334edc2b",
        "score": 50,
        "company_in_jobs": false,
        "rank": 13
      },
      {
        "kind": "recruiter",
        "name": "George S.",
        "title": "AI/ML Technical recruiter/sourcer",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/georgesleiman",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Founded and scaled the first AI/ML team, successfully hiring 58 researchers, scientists, and engineers.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "7b5ba1cd191c3866",
        "score": 50,
        "company_in_jobs": false,
        "rank": 14
      },
      {
        "kind": "recruiter",
        "name": "Ai Mong",
        "title": "Staff Technical Recruiter",
        "company": "Impulse Space",
        "linkedin_url": "https://www.linkedin.com/in/ai-mong-4247b536",
        "post_url": null,
        "location": "Staff Technical Recruiter at Impulse Space. Long Beach, California, United States",
        "hiring_for": null,
        "context": "Staff Technical Recruiter at Impulse Space. Long Beach, California, United States.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:26.920Z",
        "_id": "7eb85b28a1fe4411",
        "score": 50,
        "company_in_jobs": false,
        "rank": 15
      },
      {
        "kind": "recruiter",
        "name": "Arpita Shrivastava",
        "title": "AI-Driven Talent Acquisition Expert",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/arpita-shrivastava-94461316b",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "AI-Driven Talent Acquisition Expert. Leadership Hiring Specialist. Jersey City. US Tech Solutions.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:26.920Z",
        "_id": "98f72f910c864d14",
        "score": 50,
        "company_in_jobs": false,
        "rank": 16
      },
      {
        "kind": "recruiter",
        "name": "Fredy C.",
        "title": "Technical Recruiter | Talent Partner | Scaling AI",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/fcrecruiter",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Senior Technical Recruiter, AI & Engineering. Generative AI, Recruiting, and Talent Acquisition.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:31.615Z",
        "_id": "c40e8a1a41311073",
        "score": 50,
        "company_in_jobs": false,
        "rank": 17
      },
      {
        "kind": "recruiter",
        "name": "Shawn Bryant",
        "title": "Senior AI/ML Technical Recruiter",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/shawnbryant",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Senior AI/ML Technical Recruiter. Strategic, data-driven, metric-focused.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:31.615Z",
        "_id": "cec971419b80ade3",
        "score": 50,
        "company_in_jobs": false,
        "rank": 18
      },
      {
        "kind": "recruiter",
        "name": "Michael Ashe",
        "title": "Talent Acquisition",
        "company": "Read AI",
        "linkedin_url": "https://www.linkedin.com/in/michaelashe",
        "post_url": null,
        "location": "Michael Ashe. Talent Acquisition. Read AI. Seattle, Washington, United States",
        "hiring_for": null,
        "context": "Michael Ashe. Talent Acquisition. Read AI. Seattle, Washington, United States.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "e7510938d5b0fe8c",
        "score": 48,
        "company_in_jobs": false,
        "rank": 19
      },
      {
        "kind": "recruiter",
        "name": "Kayla Scott",
        "title": "Founding Recruiter and Head of Talent",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/kaylafscott",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Founding Recruiter and Head of Talent for Fast Growing AI SaaS Startup. Led Talent Acquisition in agency and in-house settings.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:31.615Z",
        "_id": "b234b2d1c792776a",
        "score": 48,
        "company_in_jobs": false,
        "rank": 20
      },
      {
        "kind": "recruiter",
        "name": "Scott Knowles",
        "title": "Headhunter, Executive Search Consultant",
        "company": "Greatpeople Ventures",
        "linkedin_url": "https://www.linkedin.com/in/scottknowles",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Headhunter — Executive Search Consultant. Technical Recruiter. AI. United States.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:31.615Z",
        "_id": "4fff887bb5c2f964",
        "score": 40,
        "company_in_jobs": false,
        "rank": 21
      },
      {
        "kind": "recruiter",
        "name": "Claudio Calderon",
        "title": "Talent Acquisition Manager",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/claudioacalderon",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Technical Recruiter in New York City. Ethical AI for Hiring and Talent Acquisition.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:20.096Z",
        "_id": "0367abeddf60789b",
        "score": 35,
        "company_in_jobs": false,
        "rank": 22
      },
      {
        "kind": "recruiter",
        "name": "Brian Schooley",
        "title": "Talent Acquisition Leader",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/brianschooley",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Talent Acquisition Leader — Scaling Recruiting Operations. Previously Head of Talent Acquisition at Pax8.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:26.920Z",
        "_id": "225191500e9f1a74",
        "score": 35,
        "company_in_jobs": false,
        "rank": 23
      },
      {
        "kind": "recruiter",
        "name": "Tony Cornett",
        "title": "Global VP, Talent Acquisition",
        "company": null,
        "linkedin_url": "https://www.linkedin.com/in/tonycornett-talent",
        "post_url": null,
        "location": "United States",
        "hiring_for": null,
        "context": "Global VP, Talent Acquisition, Talent Intelligence & Strategy. Leading AI. Previously Head of TA at SAP Cloud Business Group.",
        "intent": null,
        "niche": "AI / ML Talent",
        "_at": "2026-06-04T14:24:31.615Z",
        "_id": "d1a367d8998e25b2",
        "score": 35,
        "company_in_jobs": false,
        "rank": 24
      }
    ]
  }
];
